apiVersion: v2
name: itsm-ng
description: ITSM-NG Helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: "2.0.2"
home: https://itsm-ng.com/
icon: https://avatars.githubusercontent.com/u/97883427?s=200&v=4
keywords:
  - itsm
  - assets
  - helpdesk
  - management
sources:
  - https://github.com/itsmng/itsm-ng
  - https://github.com/itsmng/itsmng-docker
maintainers:
  - name: Florian Blanchet
    email: florian.blanchet@itsm-ng.com
dependencies:
  - name: mariadb-galera
    version: 14.0.14
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb-galera.enabled
