apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "itsm-ng.fullname" . }}-files
  labels:
  {{- include "itsm-ng.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.itsmweb.pvc.itsmFiles.storageRequest }}
