apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "itsm-ng.fullname" . }}-itsmweb-ingress
  labels:
  {{- include "itsm-ng.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.itsmweb.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "itsm-ng.fullname" . }}-itsmweb
            port:
              number: 80
        path: /
        pathType: Prefix
